# Generated by Django 4.2.6 on 2023-10-17 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apple_ceos', '0002_alter_ceos_first_year_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ceos',
            name='first_year_active',
        ),
    ]
