# Generated by Django 4.2.6 on 2023-10-17 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apple_ceos', '0003_remove_ceos_first_year_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeosUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('slug', models.TextField(max_length=100)),
                ('first_year_active', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Ceos',
        ),
    ]
